/** Final Act 1 Core catalogue data. Authored identities for PR4. */

import type { RelicSocketSpec } from './types'

const POWER: RelicSocketSpec = { type: 'power' }
const OPTICAL: RelicSocketSpec = { type: 'optical' }
const BALLISTIC: RelicSocketSpec = { type: 'ballistic' }
const SHIELD: RelicSocketSpec = { type: 'shield' }
const INDUSTRIAL: RelicSocketSpec = { type: 'industrial' }
const UNIVERSAL: RelicSocketSpec = { type: 'universal' }
const SHIELD_OR_UNI: RelicSocketSpec = { type: 'shield', alt: 'universal' }
const INDUSTRIAL_OR_UNI: RelicSocketSpec = { type: 'industrial', alt: 'universal' }
const OPTICAL_OR_UNI: RelicSocketSpec = { type: 'optical', alt: 'universal' }
const POWER_OR_UNI: RelicSocketSpec = { type: 'power', alt: 'universal' }

export const LEGACY_CORE_IDS = [
  'rail-driver',
  'charge-prism',
  'ion-burst',
  'swarm-rack',
  'arc-lash',
  'vector-thruster',
  'keel-baffle',
  'mirror-plate',
  'surge-capacitor',
  'salvage-rig',
  'sensor-whisker',
  'drone-bay',
  'lattice-ward',
  'slag-spit',
] as const

export const SHIP_MODULE_DEFS = [
  {
    id: 'pulse-cannon',
    name: 'Pulse Cannon',
    role: 'weapon',
    identity: 'Rapid adaptive generalist.',
    description:
      'Starter weapon. Fast adaptive bolts. Default Threat. Fires while traversing. Weak against heavy armour relative to Heavy Lance.',
    orbitRadius: 44,
    unlockSource: 'start',
    matureSockets: [POWER, OPTICAL, UNIVERSAL],
    damageBonus: 4,
    hullBonus: 0,
    damageTakenMult: 1,
    weapon: {
      name: 'Pulse',
      damage: 4,
      damagePerLevel: 1.2,
      cooldown: 0.8,
      range: 170,
      tags: ['energy'],
      hullDamage: 1,
      shieldDamage: 1,
      armorDamage: 0.25,
    },
    unlockCost: {},
  },
  {
    id: 'heavy-lance',
    name: 'Heavy Lance',
    role: 'weapon',
    identity: 'Slow line-breaking anti-heavy.',
    description:
      'Charged pierce lance. Default Heavy. Stabilises to charge and fire. Does not pre-charge before a legal firing solution.',
    orbitRadius: 56,
    unlockSource: 'wave',
    requiresBestWave: 100,
    matureSockets: [BALLISTIC, POWER, UNIVERSAL],
    damageBonus: 28,
    hullBonus: 0,
    damageTakenMult: 1,
    weapon: {
      name: 'Lance',
      damage: 28,
      damagePerLevel: 5,
      cooldown: 2.8,
      range: 260,
      tags: ['kinetic', 'pierce'],
      hullDamage: 1,
      shieldDamage: 0.7,
      armorDamage: 1,
      delivery: 'charge',
      telegraphDuration: 2.8,
    },
    unlockCost: {},
  },
  {
    id: 'flak-array',
    name: 'Flak Array',
    role: 'weapon',
    identity: 'Backlog-control specialist.',
    description:
      'Burst flak. Default Cluster. Very fast slew and a wide arc. Built to shred packs, not single heavies.',
    orbitRadius: 40,
    unlockSource: 'wave',
    requiresBestWave: 50,
    matureSockets: [BALLISTIC, POWER, UNIVERSAL],
    damageBonus: 3,
    hullBonus: 0,
    damageTakenMult: 1,
    weapon: {
      name: 'Flak',
      damage: 3,
      damagePerLevel: 0.9,
      cooldown: 1,
      range: 145,
      tags: ['kinetic', 'splash'],
      splash: 2,
      explosionRadius: 45,
      hullDamage: 1,
      shieldDamage: 0.7,
      armorDamage: 0.85,
    },
    unlockCost: {},
  },
  {
    id: 'phase-beam',
    name: 'Phase Beam',
    role: 'weapon',
    identity: 'Sustained single-target anchor.',
    description:
      'Held energy beam. Default Focus. Slows and stabilises while firing. Ramp rewards maintained contact over several seconds.',
    orbitRadius: 52,
    unlockSource: 'wave',
    requiresBestWave: 250,
    matureSockets: [OPTICAL, POWER, UNIVERSAL],
    damageBonus: 8,
    hullBonus: 0,
    damageTakenMult: 1,
    weapon: {
      name: 'Phase Beam',
      damage: 8,
      damagePerLevel: 1.6,
      cooldown: 0.42,
      range: 220,
      tags: ['energy', 'antiShield'],
      delivery: 'beam',
      hullDamage: 0.85,
      shieldDamage: 1.35,
      armorDamage: 0.3,
    },
    unlockCost: {},
  },
  {
    id: 'slag-spitter',
    name: 'Slag Spitter',
    role: 'weapon',
    identity: 'Area denial / Armor degradation.',
    description:
      'Impact plus lingering Slag/Burn. Default Cluster. Molten Pool and corrosion come from authored Mastery, not the base shot.',
    orbitRadius: 42,
    unlockSource: 'wave',
    requiresBestWave: 200,
    matureSockets: [BALLISTIC, POWER, UNIVERSAL],
    damageBonus: 4,
    hullBonus: 0,
    damageTakenMult: 1,
    weapon: {
      name: 'Slag',
      damage: 4,
      damagePerLevel: 1,
      cooldown: 1.2,
      range: 180,
      tags: ['kinetic', 'dot'],
      splash: 0,
      explosionRadius: 0,
      dotDuration: 4,
      dotDamage: 2,
      hullDamage: 1.15,
      shieldDamage: 0.55,
      armorDamage: 1.1,
    },
    unlockCost: {},
  },
  {
    id: 'plate-layer',
    name: 'Plate Layer',
    role: 'defense',
    identity: 'Large predictable Shield bank.',
    description:
      'Starter Shield. Raises the Shield ceiling with steady regen. This is a bank, not Hull regeneration and not a recovery specialist.',
    orbitRadius: 38,
    unlockSource: 'start',
    matureSockets: [SHIELD, SHIELD_OR_UNI],
    damageBonus: 0,
    hullBonus: 0,
    shieldBonus: 36,
    shieldBonusPerLevel: 6,
    shieldRegen: 0.045,
    damageTakenMult: 1,
    unlockCost: {},
  },
  {
    id: 'rapid-aegis',
    name: 'Rapid Aegis',
    role: 'defense',
    identity: 'Shield recovery specialist.',
    description:
      'Thinner Shield ceiling than Plate Layer, much faster regen. Built to outlast chip and recover from breaks, not to be a second bank.',
    orbitRadius: 40,
    unlockSource: 'material-mastery',
    matureSockets: [SHIELD, UNIVERSAL],
    damageBonus: 0,
    hullBonus: 0,
    shieldBonus: 18,
    shieldBonusPerLevel: 3,
    shieldRegen: 0.11,
    damageTakenMult: 1,
    unlockCost: {},
  },
  {
    id: 'ablative-mesh',
    name: 'Ablative Mesh',
    role: 'defense',
    identity: 'Hull / Armor / spike survival.',
    description:
      'Periodic ablative layer over Hull and Armor. Spike mitigation is bounded. Never an invulnerability loop.',
    orbitRadius: 41,
    unlockSource: 'challenge',
    matureSockets: [SHIELD, INDUSTRIAL_OR_UNI],
    damageBonus: 0,
    hullBonus: 28,
    hullBonusPerLevel: 4,
    armorBonus: 4,
    armorBonusPerLevel: 0.35,
    shieldBonus: 10,
    shieldBonusPerLevel: 1.5,
    damageTakenMult: 1,
    unlockCost: {},
  },
  {
    id: 'barrier-projector',
    name: 'Barrier Projector',
    role: 'defense',
    identity: 'Reactive emergency defense.',
    description:
      'Emergency barrier, Shield-break slow pulse, and a long-cooldown lethal intercept. Intercept is deterministic and cannot be spammed.',
    orbitRadius: 46,
    unlockSource: 'wave',
    requiresBestWave: 350,
    matureSockets: [SHIELD, OPTICAL_OR_UNI],
    damageBonus: 0,
    hullBonus: 10,
    hullBonusPerLevel: 2,
    shieldBonus: 22,
    shieldBonusPerLevel: 3,
    damageTakenMult: 1,
    unlockCost: {},
  },
  {
    id: 'salvage-beacon',
    name: 'Salvage Beacon',
    role: 'utility',
    identity: 'Visible target marking. Marked kills pay extra Salvage.',
    description:
      'Marks a high-value target. Marked kills pay extra Salvage. No extra Scrap, Foundry, or offline bonus.',
    orbitRadius: 48,
    unlockSource: 'material-mastery',
    matureSockets: [INDUSTRIAL, OPTICAL_OR_UNI],
    damageBonus: 0,
    hullBonus: 0,
    damageTakenMult: 1,
    salvageKillBonus: 0.12,
    unlockCost: {},
  },
  {
    id: 'grav-tether',
    name: 'Grav Tether',
    role: 'utility',
    identity: 'Battlefield control / formation manipulation.',
    description:
      'Slows and drags real 2D enemy positions. Default Threat. Control is geometric, not a global speed scalar.',
    orbitRadius: 50,
    unlockSource: 'wave',
    requiresBestWave: 150,
    matureSockets: [OPTICAL, INDUSTRIAL_OR_UNI],
    damageBonus: 0,
    hullBonus: 0,
    damageTakenMult: 1,
    unlockCost: {},
  },
  {
    id: 'nano-lathe',
    name: 'Nano Lathe',
    role: 'utility',
    identity: 'In-combat Hull repair.',
    description:
      'Repairs Hive Hull during active combat. Triage at low Hull. Excess repair becomes Temporary Armor. Not an offline Foundry tool.',
    orbitRadius: 43,
    unlockSource: 'foundry',
    matureSockets: [INDUSTRIAL, SHIELD_OR_UNI],
    damageBonus: 0,
    hullBonus: 8,
    hullBonusPerLevel: 1.5,
    damageTakenMult: 1,
    unlockCost: {},
  },
  {
    id: 'sensor-array',
    name: 'Sensor Array',
    role: 'utility',
    identity: 'Targeting support.',
    description:
      'Improves acquisition and slew through the targeting modifier pipeline. Helpful, not mathematically mandatory.',
    orbitRadius: 54,
    unlockSource: 'wave',
    requiresBestWave: 300,
    matureSockets: [OPTICAL, INDUSTRIAL_OR_UNI],
    damageBonus: 0,
    hullBonus: 0,
    damageTakenMult: 1,
    unlockCost: {},
  },
  {
    id: 'choir-tap',
    name: 'Choir Tap',
    role: 'utility',
    identity: 'Ash / Furnace economy. Commander / Boss resonance.',
    description:
      'Combat Ash and Furnace-facing hooks. M30 Hot Recovery and M50 Furnace Feed are Sortie-bounded and do not rewrite an already-Ignited Furnace.',
    orbitRadius: 58,
    unlockSource: 'furnace',
    matureSockets: [INDUSTRIAL, POWER_OR_UNI],
    damageBonus: 0,
    hullBonus: 0,
    damageTakenMult: 1,
    salvageKillBonus: 0,
    unlockCost: {},
  },
]
